name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    outputs:
      release_notes: ${{ steps.extract.outputs.release_notes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGES.md
        id: extract
        run: |
          TAG="${{ github.event.inputs.tag }}"
          # Extract lines between headers "## $TAG" and next "## "
          RELEASE_NOTES=$(awk "/^## $TAG$/{flag=1; next} /^## /{flag=0} flag" CHANGES.md | awk '{$1=$1};1')
          # Fallback if nothing found
          if [ -z "$RELEASE_NOTES" ]; then
            RELEASE_NOTES="Release notes for $TAG not found in CHANGES.md"
          fi
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  #publish-docker-image:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Login to Amazon ECR
  #      uses: docker/login-action@v3
  #      with:
  #        registry: ${{ secrets.ECR_REGISTRY }}
  #        username: AWS
  #        password: ${{ secrets.AWS_ECR_LOGIN_PASSWORD }}

  #    - name: Login to DockerHub
  #      uses: docker/login-action@v3
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}

  #    - name: Pull Docker images from ECR and push to DockerHub
  #      env:
  #        TAG: ${{ github.event.inputs.tag }}
  #        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  #      run: |
  #        docker pull "$ECR_REGISTRY/penpotapp/frontend:$TAG"
  #        docker pull "$ECR_REGISTRY/penpotapp/backend:$TAG"
  #        docker pull "$ECR_REGISTRY/penpotapp/exporter:$TAG"
  #        docker push "penpotapp/frontend:$TAG"
  #        docker push "penpotapp/backend:$TAG" 
  #        docker push "penpotapp/exporter:$TAG"

  create-release:
    needs: 
      - get-release-notes
      # - publish-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ needs.get-release-notes.outputs.release_notes }}
